# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-11-10 13:11:37
"""
import arcpy
from sys import argv

def MakeFullRowTable(Input_Datasets, ROW_Summary_All_Statistics="C:\\Users\\robst\\OneDrive\\Documents\\ArcGIS\\Projects\\Honolulu\\Honolulu.gdb\\ROW_Summary_All_Statistics"):  # Make Full ROW Table

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\robst\OneDrive\Documents\ArcGIS\Projects\Honolulu\Honolulu.gdb", workspace=r"C:\Users\robst\OneDrive\Documents\ArcGIS\Projects\Honolulu\Honolulu.gdb"):
        Honolulu_gdb = "C:\\Users\\robst\\OneDrive\\Documents\\ArcGIS\\Projects\\Honolulu\\Honolulu.gdb"
        ConnectionLinesTemplate = "C:\\Users\\robst\\OneDrive\\Documents\\ArcGIS\\Projects\\Honolulu\\Honolulu.gdb\\ConnectionLinesTemplate"

        # Process: Create Feature Class (Create Feature Class) (management)
        ROW_Summary_All = arcpy.management.CreateFeatureclass(out_path=Honolulu_gdb, out_name="ROW_Summary_All", geometry_type="POLYLINE", template=[ConnectionLinesTemplate], has_m="DISABLED", has_z="DISABLED", spatial_reference="PROJCS['NAD_1983_HARN_StatePlane_Hawaii_3_FIPS_5103_Feet',GEOGCS['GCS_North_American_1983_HARN',DATUM['D_North_American_1983_HARN',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',1640416.666666667],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-158.0],PARAMETER['Scale_Factor',0.99999],PARAMETER['Latitude_Of_Origin',21.16666666666667],UNIT['Foot_US',0.3048006096012192]];-16807900 -40496900 3048.00609601219;-100000 10000;-100000 10000;3.28083333333333E-03;0.001;0.001;IsHighPrecision", config_keyword="", spatial_grid_1=0, spatial_grid_2=0, spatial_grid_3=0, out_alias="")[0]

        # Process: Append (Append) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\robst\OneDrive\Documents\ArcGIS\Projects\Honolulu\Honolulu.gdb", workspace=r"C:\Users\robst\OneDrive\Documents\ArcGIS\Projects\Honolulu\Honolulu.gdb"):
            Updated_Target_Dataset = arcpy.management.Append(inputs=Input_Datasets, target=ROW_Summary_All, schema_type="TEST", field_mapping="", subtype="", expression="")[0]

        # Process: Make Feature Layer (Make Feature Layer) (management)
        ROW_Summary_Layer = "ROWSummaryAll_Layer"
        arcpy.management.MakeFeatureLayer(in_features=Updated_Target_Dataset, out_layer=ROW_Summary_Layer, where_clause="", workspace="", field_info="OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE;SEGMENTID SEGMENTID VISIBLE NONE;REVIEW REVIEW VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE")

        # Process: Summary Statistics (Summary Statistics) (analysis)
        arcpy.analysis.Statistics(in_table=ROW_Summary_Layer, out_table=ROW_Summary_All_Statistics, statistics_fields=[["Shape_Length", "MEAN"], ["Shape_Length", "MIN"], ["Shape_Length", "MAX"]], case_field=["SEGMENTID"])

if __name__ == '__main__':
    MakeFullRowTable(*argv[1:])
