in_RCLs = arcpy.GetParameterAsText(0)
rcl_join_fld = arcpy.GetParameterAsText(1)
ROW_tbl = arcpy.GetParameterAsText(2)
ROW_join_fld = arcpy.GetParameterAsText(3)
namePrefix = arcpy.GetParameterAsText(4)

arcpy.management.JoinField(in_RCLs, rcl_join_fld, ROW_tbl, ROW_join_fld, "MEAN_Shape_Length;MIN_Shape_Length;MAX_Shape_Length;MAXROW_BUF;MEANROW_BUF;MINROW_BUF")
arcpy.AddMessage("Joined {} to {} on {} and {}".format(in_RCLs,rcl_join_fld,ROW_tbl,ROW_join_fld))

lyrName = "in_memory\\{}_RCLJoinToROW".format(namePrefix)
result = arcpy.management.MakeFeatureLayer(in_RCLs, lyrName, "MAXROW_BUF IS NOT NULL And MINROW_BUF IS NOT NULL And MEANROW_BUF IS NOT NULL", None, "OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE;SEGMENTID SEGMENTID VISIBLE NONE;STREETID STREETID VISIBLE NONE;FULLNAME FULLNAME VISIBLE NONE;PREDIR PREDIR VISIBLE NONE;NAME NAME VISIBLE NONE;PROPERNAME PROPERNAME VISIBLE NONE;TYPE TYPE VISIBLE NONE;POSTDIR POSTDIR VISIBLE NONE;SCLL SCLL VISIBLE NONE;SCLH SCLH VISIBLE NONE;SCRL SCRL VISIBLE NONE;SCRH SCRH VISIBLE NONE;CLASS CLASS VISIBLE NONE;STREET_CLA STREET_CLA VISIBLE NONE;ZIPCODER ZIPCODER VISIBLE NONE;ZIPCODEL ZIPCODEL VISIBLE NONE;TOWNL TOWNL VISIBLE NONE;TOWNR TOWNR VISIBLE NONE;NEIGHBORL NEIGHBORL VISIBLE NONE;NEIGHBORR NEIGHBORR VISIBLE NONE;TRACTL TRACTL VISIBLE NONE;TRACTR TRACTR VISIBLE NONE;ONEWAY ONEWAY VISIBLE NONE;TELEV TELEV VISIBLE NONE;FELEV FELEV VISIBLE NONE;EDITTYPE EDITTYPE VISIBLE NONE;E911 E911 VISIBLE NONE;TRANSITION TRANSITION VISIBLE NONE;SHARED SHARED VISIBLE NONE;BUILT BUILT VISIBLE NONE;REVISEDATE REVISEDATE VISIBLE NONE;OWNER OWNER VISIBLE NONE;MAINTAINER MAINTAINER VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;MAXROW_BUF MAXROW_BUF VISIBLE NONE;MINROW_BUF MINROW_BUF VISIBLE NONE;MEANROW_BUF MEANROW_BUF VISIBLE NONE")

arcpy.SetParameter(5,result.getOutput(0))
